---
- name: Enable Apache mods
  apache2_module:
    name: "{{ item }}"
    state: present
  loop: "{{ apache_mods_enabled }}"
  notify: __apache_restart

- name: Disable Apache mods
  apache2_module:
    name: "{{ item }}"
    state: absent
  loop: "{{ apache_mods_disabled }}"
  notify: __apache_restart

- name: Remove default vhost in sites-enabled
  file:
    path: "{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhost_name }}"
    state: absent
  notify: __apache_restart

- name: Add apache vhosts configuration
  template:
    src: owncloud.conf.j2
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhost_name }}"
    owner: root
    group: root
    mode: 0644
  notify: __apache_restart

- name: Add vhost symlink in sites-enabled
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhost_name }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhost_name }}"
    state: link
  notify: __apache_restart
