---
- include_vars: "{{ var_files }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "vars"
    var_files: "{{ lookup('first_found', params, errors='ignore') }}"
  when: var_files | lenght > 0

- include_tasks: overwrites.yml

- include_tasks: "setup.yml"
- include_tasks: "{{ task_files }}"
  vars:
    params:
      files:
        - "configure-{{ ansible_os_family | lower }}.yml"
      paths:
        - "tasks"
    task_files: "{{ lookup('first_found', params, errors='ignore') }}"
  when: task_files | length > 0

- include_tasks: tls.yml
- include_tasks: post.yml
